%% These are the runs used to generate figures for Paper 1

%% 3DLJ (Lancon) - Velocity Profiles 
% run 0 - Quench Duration = 1e4 t0 - Strain Rate = MULTIPLE 1/t0 
% Used to obtain velocity profiles at 100%.

close all

structure_1 = '~/Desktop/HHPC/Research/runs/LJ/Lancon-et-al/run0/shear/t0_1e4/sr_00002/data/MATLAB/';
structure_2 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run0/shear/t0_1e4/sr_00010/data/MATLAB/';
structure_3 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run0/shear/t0_1e4/sr_00050/data/MATLAB/';

showBanding({structure_1},...
    'system','lancon',...
    'nBins',100,...
    'span',50,...
    'averagealong','strainrate',...
    'quenchduration',{'1e4','1e5','1e6'},...
    'strainrate','0.00002',...
    'runnumber','0')

%% 3DLJ (Lancon) - Velocity Profiles 
% run 0 - Quench Duration = 1e4 t0 - Strain Rate = MULTIPLE 1/t0 
% Used to obtain velocity profiles at 100%.

close all

structure_1 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run0/shear/t0_1e4/sr_00002/data/MATLAB/';
structure_2 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run0/shear/t0_1e4/sr_00010/data/MATLAB/';
structure_3 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run0/shear/t0_1e4/sr_00050/data/MATLAB/';

showBanding({structure_1,structure_2,structure_3},...
    'system','lancon',...
    'nBins',100,...
    'span',50,...
    'averagealong','strainrate',...
    'quenchduration',{'1e4','1e5','1e6'},...
    'strainrate','0.00002',...
    'runnumber','0')

%% 3DLJ (Lancon) - Velocity Profiles 
% run 1 - Quench Duration = 1e4 t0 - Strain Rate = MULTIPLE 1/t0 
% Used to obtain velocity profiles at 100%.

close all

structure_1 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run1/shear/t0_1e4/sr_00002/data/MATLAB/';
structure_2 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run1/shear/t0_1e4/sr_00010/data/MATLAB/';
structure_3 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run1/shear/t0_1e4/sr_00050/data/MATLAB/';

showBanding({structure_1,structure_2,structure_3},...
    'system','lancon',...
    'nBins',100,...
    'span',50,...
    'averagealong','strainrate',...
    'quenchduration',{'1e4','1e5','1e6'},...
    'strainrate','0.00002',...
    'runnumber','0')

%% 3DLJ (Lancon) - Velocity Profiles 
% run 1 - Quench Duration = 1e4 t0 - Strain Rate = MULTIPLE 1/t0 
% Used to obtain velocity profiles at 100%.

close all

structure_1 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run2/shear/t0_1e4/sr_00002/data/MATLAB/';
structure_2 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run2/shear/t0_1e4/sr_00010/data/MATLAB/';
structure_3 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run2/shear/t0_1e4/sr_00050/data/MATLAB/';

showBanding({structure_1,structure_2,structure_3},...
    'system','lancon',...
    'nBins',100,...
    'span',50,...
    'averagealong','strainrate',...
    'quenchduration',{'1e4','1e5','1e6'},...
    'strainrate','0.00002',...
    'runnumber','0')

%% 3DLJ (Lancon) - Velocity Profiles 
% run 0 - Quench Duration = 1e5 t0 - Strain Rate = MULTIPLE 1/t0 
% Used to obtain velocity profiles at 100%.

close all

structure_1 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run0/shear/t0_1e5/sr_00002/data/MATLAB/';
structure_2 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run0/shear/t0_1e5/sr_00010/data/MATLAB/';
structure_3 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run0/shear/t0_1e5/sr_00050/data/MATLAB/';

showBanding({structure_1,structure_2,structure_3},...
    'system','lancon',...
    'nBins',100,...
    'span',50,...
    'averagealong','strainrate',...
    'quenchduration',{'1e4','1e5','1e6'},...
    'strainrate','0.00002',...
    'runnumber','0')

%% 3DLJ (Lancon) - Velocity Profiles 
% run 0 - Quench Duration = 1e5 t0 - Strain Rate = MULTIPLE 1/t0 
% Used to obtain velocity profiles at 100%.

close all

structure_1 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run1/shear/t0_1e5/sr_00002/data/MATLAB/';
structure_2 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run1/shear/t0_1e5/sr_00010/data/MATLAB/';
structure_3 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run1/shear/t0_1e5/sr_00050/data/MATLAB/';

showBanding({structure_1,structure_2,structure_3},...
    'system','lancon',...
    'nBins',100,...
    'span',50,...
    'averagealong','strainrate',...
    'quenchduration',{'1e4','1e5','1e6'},...
    'strainrate','0.00002',...
    'runnumber','0')

%% 3DLJ (Lancon) - Velocity Profiles 
% run 0 - Quench Duration = 1e5 t0 - Strain Rate = MULTIPLE 1/t0 
% Used to obtain velocity profiles at 100%.

close all

structure_1 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run2/shear/t0_1e5/sr_00002/data/MATLAB/';
structure_2 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run2/shear/t0_1e5/sr_00010/data/MATLAB/';
structure_3 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run2/shear/t0_1e5/sr_00050/data/MATLAB/';

showBanding({structure_1,structure_2,structure_3},...
    'system','lancon',...
    'nBins',100,...
    'span',50,...
    'averagealong','strainrate',...
    'quenchduration',{'1e4','1e5','1e6'},...
    'strainrate','0.00002',...
    'runnumber','0')


%% 3DLJ (Lancon) - Velocity Profiles 
% run 0 - Quench Duration = 1e6 t0 - Strain Rate = MULTIPLE 1/t0 
% Used to obtain velocity profiles at 100%.

close all

structure_1 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run0/shear/t0_1e6/sr_00002/data/MATLAB/';
structure_2 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run0/shear/t0_1e6/sr_00010/data/MATLAB/';
structure_3 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run0/shear/t0_1e6/sr_00050/data/MATLAB/';

showBanding({structure_1,structure_2,structure_3},...
    'system','lancon',...
    'nBins',100,...
    'span',50,...
    'averagealong','strainrate',...
    'quenchduration',{'1e4','1e5','1e6'},...
    'strainrate','0.00002',...
    'runnumber','0')

%% 3DLJ (Lancon) - Velocity Profiles 
% run 1 - Quench Duration = 1e6 t0 - Strain Rate = MULTIPLE 1/t0 
% Used to obtain velocity profiles at 100%.

close all

structure_1 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run1/shear/t0_1e6/sr_00002/data/MATLAB/';
structure_2 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run1/shear/t0_1e6/sr_00010/data/MATLAB/';
structure_3 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run1/shear/t0_1e6/sr_00050/data/MATLAB/';

showBanding({structure_1,structure_2,structure_3},...
    'system','lancon',...
    'nBins',100,...
    'span',50,...
    'averagealong','strainrate',...
    'quenchduration',{'1e4','1e5','1e6'},...
    'strainrate','0.00002',...
    'runnumber','1')

%% 3DLJ (Lancon) - Velocity Profiles 
% run 1 - Quench Duration = 1e6 t0 - Strain Rate = MULTIPLE 1/t0 
% Used to obtain velocity profiles at 100%.

close all

structure_1 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run2/shear/t0_1e6/sr_00002/data/MATLAB/';
structure_2 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run2/shear/t0_1e6/sr_00010/data/MATLAB/';
structure_3 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run2/shear/t0_1e6/sr_00050/data/MATLAB/';

showBanding({structure_1,structure_2,structure_3},...
    'system','lancon',...
    'nBins',100,...
    'span',50,...
    'averagealong','strainrate',...
    'quenchduration',{'1e4','1e5','1e6'},...
    'strainrate','0.00002',...
    'runnumber','2')

%% Cu64Zr36 - Velocity Profiles
% THESE RUNS HAVE NOT BEEN USED TO GENERATE IMAGES, JUST TABLES

close all

system_1 = '/Volumes/MARCC/scratch/CuZr/4x20x1_Cu64Zr36_Glasses/run1/shear/qr_1e09/sr_00050/data/MATLAB/';
system_2 = '/Volumes/MARCC/scratch/CuZr/4x20x1_Cu64Zr36_Glasses/run1/shear/qr_1e10/sr_00050/data/MATLAB/';
system_3 = '/Volumes/MARCC/scratch/CuZr/4x20x1_Cu64Zr36_Glasses/run1/shear/qr_1e11/sr_00050/data/MATLAB/';

showBanding({system_1,system_2,system_3},...
    'system','cz',...
    'nBins',100,...
    'span',100,...
    'averagealong','strainrate',...
    'quenchduration',{'.100','.010','.001'},...
    'strainrate','0.0005',...
    'runnumber','1')

%% Cu64Zr36 - Velocity Profiles - Run 2
% Quench Rate = 0.001 K/ps, ALL STRAIN RATES

close all

system_1 = '/Volumes/MARCC/scratch/CuZr/4x20x1_Cu64Zr36_Glasses/run2/shear/qr_1e09/sr_00050/data/MATLAB/';
system_2 = '/Volumes/MARCC/scratch/CuZr/4x20x1_Cu64Zr36_Glasses/run2/shear/qr_1e09/sr_00010/data/MATLAB/';
system_3 = '/Volumes/MARCC/scratch/CuZr/4x20x1_Cu64Zr36_Glasses/run2/shear/qr_1e09/sr_00002/data/MATLAB/';

showBanding({system_1,system_2,system_3},...
    'system','cz',...
    'nBins',100,...
    'span',50,...
    'averagealong','strainrate',...
    'quenchduration',{'.100','.010','.001'},...
    'strainrate','0.0005',...
    'runnumber','2')

%% Cu64Zr36 - Velocity Profiles - Run 2
% Quench Rate = 0.001 K/ps, ALL STRAIN RATES

close all

system_1 = '/Volumes/MARCC/scratch/CuZr/4x20x1_Cu64Zr36_Glasses/run2/shear/qr_1e10/sr_00050/data/MATLAB/';
system_2 = '/Volumes/MARCC/scratch/CuZr/4x20x1_Cu64Zr36_Glasses/run2/shear/qr_1e10/sr_00010/data/MATLAB/';
system_3 = '/Volumes/MARCC/scratch/CuZr/4x20x1_Cu64Zr36_Glasses/run2/shear/qr_1e10/sr_00002/data/MATLAB/';

showBanding({system_1,system_2,system_3},...
    'system','cz',...
    'nBins',100,...
    'span',50,...
    'averagealong','strainrate',...
    'quenchduration',{'.100','.010','.001'},...
    'strainrate','0.0005',...
    'runnumber','2')

%% Cu64Zr36 - Velocity Profiles - Run 2
% Quench Rate = 0.100 K/ps, ALL STRAIN RATES

close all

system_1 = '/Volumes/MARCC/scratch/CuZr/4x20x1_Cu64Zr36_Glasses/run2/shear/qr_1e11/sr_00050/data/MATLAB/';
system_2 = '/Volumes/MARCC/scratch/CuZr/4x20x1_Cu64Zr36_Glasses/run2/shear/qr_1e11/sr_00010/data/MATLAB/';
system_3 = '/Volumes/MARCC/scratch/CuZr/4x20x1_Cu64Zr36_Glasses/run2/shear/qr_1e11/sr_00002/data/MATLAB/';

showBanding({system_1,system_2,system_3},...
    'system','cz',...
    'nBins',100,...
    'span',50,...
    'averagealong','strainrate',...
    'quenchduration',{'.100','.010','.001'},...
    'strainrate','0.0005',...
    'runnumber','2')

%% aSi - run 0 - Strain Rate = 0.0005 1/ps
% Quench Rate = 1.00 K/ps

close all

structure_1 = '/Volumes/MARCC/scratch/Si/run0/shear/qr_1e12/sr_00050/data/MATLAB/';
structure_2 = '/Volumes/MARCC/scratch/Si/run0/shear/qr_1e12/sr_00010/data/MATLAB/';
structure_3 = '/Volumes/MARCC/scratch/Si/run0/shear/qr_1e12/sr_00002/data/MATLAB/';

showBanding({structure_1,structure_2,structure_3},...
    'system','tanguy',...
    'nBins',100,...
    'span',50,...
    'averagealong','strainrate',...
    'quenchduration',{'1.00','0.10','0.01'},...
    'strainrate','0.0005',...
    'runnumber','0')

%% aSi - run 0 - Strain Rate = 0.0005 1/ps
% Quench Rate = 0.10 K/ps

close all

structure_1 = '/Volumes/MARCC/scratch/Si/run0/shear/qr_1e11/sr_00050/data/MATLAB/';
structure_2 = '/Volumes/MARCC/scratch/Si/run0/shear/qr_1e11/sr_00010/data/MATLAB/';
structure_3 = '/Volumes/MARCC/scratch/Si/run0/shear/qr_1e11/sr_00002/data/MATLAB/';

showBanding({structure_1,structure_2,structure_3},...
    'system','tanguy',...
    'nBins',100,...
    'span',50,...
    'averagealong','strainrate',...
    'quenchduration',{'1.00','0.10','0.01'},...
    'strainrate','0.0005',...
    'runnumber','0')

%% aSi - run 0 - Strain Rate = 0.0005 1/ps
% Quench Rate = 0.01 K/ps

close all

structure_1 = '/Volumes/MARCC/scratch/Si/run0/shear/qr_1e10/sr_00050/data/MATLAB/';
structure_2 = '/Volumes/MARCC/scratch/Si/run0/shear/qr_1e10/sr_00010/data/MATLAB/';
structure_3 = '/Volumes/MARCC/scratch/Si/run0/shear/qr_1e10/sr_00002/data/MATLAB/';

showBanding({structure_1,structure_2,structure_3},...
    'system','tanguy',...
    'nBins',100,...
    'span',50,...
    'averagealong','strainrate',...
    'quenchduration',{'1.00','0.10','0.01'},...
    'strainrate','0.0005',...
    'runnumber','0')
