%% Kob-Andersen Binary - Run 0 - Strain Rate = 0.0005 1/t0
close all

structure_1 = '/Volumes/HHPC/Research/runs/LJ/Kob-Andersen/AR_4x20x1/run0/shear/t0_1e3/sr_00002/data/MATLAB/';
structure_2 = '/Volumes/HHPC/Research/runs/LJ/Kob-Andersen/AR_4x20x1/run0/shear/t0_1e4/sr_00002/data/MATLAB/';
structure_3 = '/Volumes/HHPC/Research/runs/LJ/Kob-Andersen/AR_4x20x1/run0/shear/t0_1e5/sr_00002/data/MATLAB/';
% structure_1 = '/Volumes/HHPC/Research/runs/LJ/Kob-Andersen/AR_4x20x1/run0/shear/t0_1e3/sr_00002/data/MATLAB/';

showBanding({structure_3},...
    'system','kobandersen',...
    'nBins',100,...
    'span',20,...
    'averagealong','strainrate',...
    'quenchduration',{'1e3','1e4','1e5'},...
    'strainrate','0.00002',...
    'runnumber','0')

%% Kob-Andersen Binary - Run 0 - Strain Rate = 0.0001 1/t0
close all

structure_1 = '/Volumes/HHPC/Research/runs/LJ/Kob-Andersen/AR_4x20x1/run0/shear/t0_1e3/sr_00010/data/MATLAB/';
structure_2 = '/Volumes/HHPC/Research/runs/LJ/Kob-Andersen/AR_4x20x1/run0/shear/t0_1e4/sr_00010/data/MATLAB/';
structure_3 = '/Volumes/HHPC/Research/runs/LJ/Kob-Andersen/AR_4x20x1/run0/shear/t0_1e5/sr_00010/data/MATLAB/';


showBanding({structure_1,structure_2,structure_3},...
    'system','kobandersen',...
    'nBins',100,...
    'span',20,...
    'averagealong','strainrate',...
    'quenchduration',{'1e3','1e4','1e5'},...
    'strainrate','0.0001',...
    'runnumber','0')

%% Kob-Andersen Binary - Run 1 - Strain Rate = 0.0005 1/t0
close all

structure_1 = '/Volumes/HHPC/Research/runs/LJ/Kob-Andersen/AR_4x20x1/run1/shear/t0_1e3/sr_00050/data/MATLAB/';
structure_2 = '/Volumes/HHPC/Research/runs/LJ/Kob-Andersen/AR_4x20x1/run1/shear/t0_1e4/sr_00050/data/MATLAB/';
structure_3 = '/Volumes/HHPC/Research/runs/LJ/Kob-Andersen/AR_4x20x1/run1/shear/t0_1e5/sr_00050/data/MATLAB/';


showBanding({structure_1,structure_2,structure_3},...
    'system','kobandersen',...
    'nBins',100,...
    'span',20,...
    'averagealong','strainrate',...
    'quenchduration',{'1e3','1e4','1e5'},...
    'strainrate','0.0005',...
    'runnumber','1')

%% Kob-Andersen Binary - Run 1 - Strain Rate = 0.0001 1/t0
close all

structure_1 = '/Volumes/HHPC/Research/runs/LJ/Kob-Andersen/AR_4x20x1/run1/shear/t0_1e3/sr_00010/data/MATLAB/';
structure_2 = '/Volumes/HHPC/Research/runs/LJ/Kob-Andersen/AR_4x20x1/run1/shear/t0_1e4/sr_00010/data/MATLAB/';
structure_3 = '/Volumes/HHPC/Research/runs/LJ/Kob-Andersen/AR_4x20x1/run1/shear/t0_1e5/sr_00010/data/MATLAB/';


showBanding({structure_1,structure_2,structure_3},...
    'system','kobandersen',...
    'nBins',100,...
    'span',20,...
    'averagealong','strainrate',...
    'quenchduration',{'1e3','1e4','1e5'},...
    'strainrate','0.0001',...
    'runnumber','1')

%% Kob-Andersen Binary - Run 2 - Strain Rate = 0.0005 1/t0
close all

structure_1 = '/Volumes/HHPC/Research/runs/LJ/Kob-Andersen/AR_4x20x1/run2/shear/t0_1e3/sr_00050/data/MATLAB/';
structure_2 = '/Volumes/HHPC/Research/runs/LJ/Kob-Andersen/AR_4x20x1/run2/shear/t0_1e4/sr_00050/data/MATLAB/';
structure_3 = '/Volumes/HHPC/Research/runs/LJ/Kob-Andersen/AR_4x20x1/run2/shear/t0_1e5/sr_00050/data/MATLAB/';


showBanding({structure_1,structure_2,structure_3},...
    'system','kobandersen',...
    'nBins',100,...
    'span',20,...
    'averagealong','strainrate',...
    'quenchduration',{'1e3','1e4','1e5'},...
    'strainrate','0.0005',...
    'runnumber','2')

%% Kob-Andersen Binary - Run 2 - Strain Rate = 0.0001 1/t0
close all

structure_1 = '/Volumes/HHPC/Research/runs/LJ/Kob-Andersen/AR_4x20x1/run2/shear/t0_1e3/sr_00010/data/MATLAB/';
structure_2 = '/Volumes/HHPC/Research/runs/LJ/Kob-Andersen/AR_4x20x1/run2/shear/t0_1e4/sr_00010/data/MATLAB/';
structure_3 = '/Volumes/HHPC/Research/runs/LJ/Kob-Andersen/AR_4x20x1/run2/shear/t0_1e5/sr_00010/data/MATLAB/';


showBanding({structure_1,structure_2,structure_3},...
    'system','kobandersen',...
    'nBins',100,...
    'span',20,...
    'averagealong','strainrate',...
    'quenchduration',{'1e3','1e4','1e5'},...
    'strainrate','0.0001',...
    'runnumber','2')


%% Kob-Andersen Binary - Run 2 - Strain Rate = 0.0005 1/t0
close all

structure_1 = '/Volumes/HHPC/Research/runs/LJ/Kob-Andersen/AR_4x20x1/regional_therm/trial_06/data/MATLAB/';
structure_1 = '/Volumes/HHPC/Research/runs/LJ/Kob-Andersen/AR_4x20x1/regional_therm/1region/data/MATLAB/';
structure_2 = '/Volumes/HHPC/Research/runs/LJ/Kob-Andersen/AR_4x20x1/regional_therm/2regions/data/MATLAB/';
structure_3 = '/Volumes/HHPC/Research/runs/LJ/Kob-Andersen/AR_4x20x1/regional_therm/3regions/data/MATLAB/';
structure_1 = '/Volumes/HHPC/Research/runs/LJ/Kob-Andersen/AR_4x20x1/regional_therm/trial_05/10regions/data/MATLAB/';
structure_1 = '/Volumes/HHPC/Research/runs/LJ/Kob-Andersen/AR_4x20x1/regional_therm/trial_06/1region/data/MATLAB/';
structure_2 = '/Volumes/HHPC/Research/runs/LJ/Kob-Andersen/AR_4x20x1/regional_therm/trial_06/2regions/data/MATLAB/';
structure_3 = '/Volumes/HHPC/Research/runs/LJ/Kob-Andersen/AR_4x20x1/regional_therm/trial_06/3regions/data/MATLAB/';


% structure_1 = '/Volumes/HHPC/Research/runs/LJ/Kob-Andersen/AR_4x20x1/regional_therm/4regions/data/MATLAB/';
% structure_1 = '/Volumes/HHPC/Research/runs/LJ/Kob-Andersen/AR_4x20x1/regional_therm/5regions/data/MATLAB/';
% structure_1 = '/Volumes/MCCOY/Research/Shear_Banding/KobAnd/';

showBanding({structure_1,structure_2,structure_3},...
    'system','kobandersen',...
    'nBins',100,...
    'span',20,...
    'averagealong','strainrate',...
    'quenchduration',{'1e3','1e4','1e5'},...
    'strainrate','0.0005',...
    'runnumber','2')