%% 3DLJ Lancon - run0 - Strain Rate = MULTIPLE 1/t0 
close all

structure_1 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run0/shear/t0_1e4/sr_00002/data/MATLAB/';
structure_2 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run0/shear/t0_1e4/sr_00010/data/MATLAB/';
structure_3 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run0/shear/t0_1e4/sr_00050/data/MATLAB/';

showBanding({structure_1,structure_2,structure_3},...
    'system','lancon',...
    'nBins',100,...
    'span',.5,...
    'averagealong','fixedpoint',...
    'quenchduration',{'1e4','1e5','1e6'},...
    'strainrate','0.00002',...
    'runnumber','0')

%% Lancon - run0 - Strain Rate = 0.0001 1/t0
close all

structure_1 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run0/shear/t0_1e4/sr_00010/data/MATLAB/';
structure_2 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run0/shear/t0_1e5/sr_00010/data/MATLAB/';
structure_3 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run0/shear/t0_1e6/sr_00010/data/MATLAB/';

showBanding({structure_1,structure_2,structure_3},...
    'system','lancon',...
    'nBins',50,...
    'span',20,...
    'averagealong','strainrate',...
    'quenchduration',{'1e4','1e5','1e6'},...
    'strainrate','0.0001',...
    'runnumber','0')

%% Lancon - run0 - Strain Rate = 0.0005 1/t0
close all

structure_1 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run0/shear/t0_1e4/sr_00050/data/MATLAB/';
structure_2 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run0/shear/t0_1e5/sr_00050/data/MATLAB/';
structure_3 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run0/shear/t0_1e6/sr_00050/data/MATLAB/';

showBanding({structure_1,structure_2,structure_3},...
    'system','lancon',...
    'nBins',100,...
    'span',20,...
    'averagealong','strainrate',...
    'quenchduration',{'1e4','1e5','1e6'},...
    'strainrate','0.0005',...
    'runnumber','0')

%% Lancon - run1 - Strain Rate = 0.0001 1/t0
close all

structure_1 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run1/shear/t0_1e4/sr_00010/data/MATLAB/';
structure_2 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run1/shear/t0_1e5/sr_00010/data/MATLAB/';
structure_3 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run1/shear/t0_1e6/sr_00010/data/MATLAB/';

showBanding({structure_1,structure_2,structure_3},...
    'system','lancon',...
    'nBins',100,...
    'span',20,...
    'averagealong','strainrate',...
    'quenchduration',{'1e4','1e5','1e6'},...
    'strainrate','0.0001',...
    'runnumber','1')

%% Lancon - run1 - Strain Rate = 0.0005 1/t0
close all

structure_1 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run1/shear/t0_1e4/sr_00050/data/MATLAB/';
structure_2 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run1/shear/t0_1e5/sr_00050/data/MATLAB/';
structure_3 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run1/shear/t0_1e6/sr_00050/data/MATLAB/';

showBanding({structure_1,structure_2,structure_3},...
    'system','lancon',...
    'nBins',100,...
    'span',20,...
    'averagealong','strainrate',...
    'quenchduration',{'1e4','1e5','1e6'},...
    'strainrate','0.0005',...
    'runnumber','1')

%% Lancon - run2 - Strain Rate = 0.0001 1/t0
close all

structure_1 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run2/shear/t0_1e4/sr_00010/data/MATLAB/';
structure_2 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run2/shear/t0_1e5/sr_00010/data/MATLAB/';
structure_3 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run2/shear/t0_1e6/sr_00010/data/MATLAB/';

showBanding({structure_1,structure_2,structure_3},...
    'system','lancon',...
    'nBins',100,...
    'span',20,...
    'averagealong','strainrate',...
    'quenchduration',{'1e4','1e5','1e6'},...
    'strainrate','0.0001',...
    'runnumber','2')

%% Lancon - run2 - Strain Rate = 0.0005 1/t0
close all

structure_1 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run2/shear/t0_1e4/sr_00050/data/MATLAB/';
structure_2 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run2/shear/t0_1e5/sr_00050/data/MATLAB/';
structure_3 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run2/shear/t0_1e6/sr_00050/data/MATLAB/';

showBanding({structure_1,structure_2,structure_3},...
    'system','lancon',...
    'nBins',100,...
    'span',20,...
    'averagealong','strainrate',...
    'quenchduration',{'1e4','1e5','1e6'},...
    'strainrate','0.0005',...
    'runnumber','2')

%% Lancon - TEST TIGHT DAMPING 
close all

structure_1 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run0/shear/t0_1e4/sr_00010/tdamp_0.0002_tstep_0.001/data/MATLAB/';
structure_2 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run2/shear/t0_1e5/sr_00050/data/MATLAB/';
structure_3 = '/Volumes/HHPC/Research/runs/LJ/Lancon-et-al/run2/shear/t0_1e6/sr_00050/data/MATLAB/';

showBanding({structure_1},...
    'system','lancon',...
    'nBins',100,...
    'span',20,...
    'averagealong','strainrate',...
    'quenchduration',{'1e4','1e5','1e6'},...
    'strainrate','0.0001',...
    'runnumber','0')